// Package changespec provides types and validation for ChangeSpec 1.0 events.
//
// A ChangeSpec event is a JSON object describing a software change from a
// vendor or package maintainer. This package defines Go types that match the
// ChangeSpec 1.0 JSON Schema and a Validate function that parses and validates
// raw JSON.
//
// Specification: https://github.com/changespec/changespec/blob/main/spec/spec.md
package changespec

// SpecVersion is the ChangeSpec version this package implements.
const SpecVersion = "1.0"

// Category classifies the type of change in an event.
type Category string

const (
	// CategoryAPIBreaking is a backward-incompatible API or SDK change.
	CategoryAPIBreaking Category = "api_breaking"
	// CategoryAPIDeprecation marks a feature deprecated with a future removal date.
	CategoryAPIDeprecation Category = "api_deprecation"
	// CategorySecurity is a security vulnerability, patch, or advisory.
	CategorySecurity Category = "security"
	// CategoryDataHandling is a change to data storage, processing, or subprocessors.
	CategoryDataHandling Category = "data_handling"
	// CategoryLiability is a change to TOS terms affecting legal liability.
	CategoryLiability Category = "liability"
	// CategoryPricing is a change to pricing, billing, or plan limits.
	CategoryPricing Category = "pricing"
	// CategoryTOS is a general terms of service or policy change.
	CategoryTOS Category = "tos"
	// CategoryCosmetic is a documentation or visual change with no functional impact.
	CategoryCosmetic Category = "cosmetic"
	// CategoryInformational is an announcement or update requiring no action.
	CategoryInformational Category = "informational"
)

// Severity communicates urgency and potential impact.
type Severity string

const (
	// SeverityCritical requires immediate action.
	SeverityCritical Severity = "critical"
	// SeverityHigh requires action within days to weeks.
	SeverityHigh Severity = "high"
	// SeverityMedium requires action before a future deadline.
	SeverityMedium Severity = "medium"
	// SeverityLow is advisory with no immediate action required.
	SeverityLow Severity = "low"
	// SeverityInformational requires no action.
	SeverityInformational Severity = "informational"
)

// SourceType indicates how the event was produced and the trust level of its classification.
type SourceType string

const (
	// SourcePublisherVerified means the vendor pushed this event directly.
	SourcePublisherVerified SourceType = "publisher_verified"
	// SourceCrawled means the event was generated by automated change detection.
	SourceCrawled SourceType = "crawled"
	// SourceCommunity means the event was submitted by a community member.
	SourceCommunity SourceType = "community"
)

// ReviewerRole is an advisory routing hint for which team should review an event.
type ReviewerRole string

const (
	ReviewerEngineering ReviewerRole = "engineering"
	ReviewerSecurity    ReviewerRole = "security"
	ReviewerLegal       ReviewerRole = "legal"
	ReviewerCompliance  ReviewerRole = "compliance"
	ReviewerProcurement ReviewerRole = "procurement"
	ReviewerManagement  ReviewerRole = "management"
)

// Signature is an Ed25519 signature block present on publisher_verified events.
type Signature struct {
	// Alg is the signature algorithm. Always "ed25519" in ChangeSpec 1.0.
	Alg string `json:"alg"`
	// KeyID identifies the signing key for public key lookup.
	KeyID string `json:"key_id"`
	// Value is the base64url-encoded Ed25519 signature (64 bytes, no padding).
	Value string `json:"value"`
	// SignedFields is the ordered list of field names included in the signature input.
	SignedFields []string `json:"signed_fields"`
}

// Event is a ChangeSpec 1.0 event. All required fields are non-pointer types.
// Optional fields use pointer types so that absent fields are nil rather than
// zero values, preserving the distinction between "not set" and "set to empty".
type Event struct {
	// --- Required fields ---

	// SpecVersion must be "1.0".
	SpecVersion string `json:"specversion"`
	// ID is a globally unique event identifier. Stable across re-deliveries.
	ID string `json:"id"`
	// VendorID identifies the vendor or package. Namespaced format, e.g. "npm:lodash".
	VendorID string `json:"vendor_id"`
	// Category classifies the type of change.
	Category Category `json:"category"`
	// Severity communicates urgency and potential impact.
	Severity Severity `json:"severity"`
	// Title is a short human-readable change description. No newlines.
	Title string `json:"title"`
	// Summary is a 1-5 sentence plain-text description of the change and its impact.
	Summary string `json:"summary"`
	// PublishedAt is the RFC 3339 timestamp when this event was published.
	PublishedAt string `json:"published_at"`
	// SourceType indicates how the event was produced.
	SourceType SourceType `json:"source_type"`

	// --- Optional fields ---

	// EffectiveDate is the YYYY-MM-DD date when the change takes effect.
	EffectiveDate *string `json:"effective_date,omitempty"`
	// SourceURL is the URL of the primary source document.
	SourceURL *string `json:"source_url,omitempty"`
	// AffectedVersions is a semver range (npm syntax) of affected versions.
	AffectedVersions *string `json:"affected_versions,omitempty"`
	// FixedInVersion is the semver version where this issue is resolved.
	FixedInVersion *string `json:"fixed_in_version,omitempty"`
	// MigrationHint is a short plain-text action description for consumers.
	MigrationHint *string `json:"migration_hint,omitempty"`
	// MigrationURL is the URL of a detailed migration guide.
	MigrationURL *string `json:"migration_url,omitempty"`
	// ConfidenceScore is the producer's confidence in the classification [0.0, 1.0].
	ConfidenceScore *float64 `json:"confidence_score,omitempty"`
	// SunsetDate is the YYYY-MM-DD date when a deprecated feature is removed.
	SunsetDate *string `json:"sunset_date,omitempty"`
	// CVEID is the CVE identifier for security events, e.g. "CVE-2024-12345".
	CVEID *string `json:"cve_id,omitempty"`
	// CVSSScore is the CVSS base score (0.0-10.0) for security events.
	CVSSScore *float64 `json:"cvss_score,omitempty"`
	// CVSSVector is the CVSS vector string for security events.
	CVSSVector *string `json:"cvss_vector,omitempty"`
	// AffectedSystems lists named systems within the vendor that are affected.
	AffectedSystems []string `json:"affected_systems,omitempty"`
	// AffectedSections lists document section headers affected (for TOS/DPA changes).
	AffectedSections []string `json:"affected_sections,omitempty"`
	// ActionRequired indicates whether consumers must take action.
	ActionRequired *bool `json:"action_required,omitempty"`
	// RecommendedReviewers lists advisory routing hints for which teams to notify.
	RecommendedReviewers []ReviewerRole `json:"recommended_reviewers,omitempty"`
	// Tags are freeform lowercase tags for filtering.
	Tags []string `json:"tags,omitempty"`
	// Signature is the Ed25519 signature block for publisher_verified events.
	Signature *Signature `json:"signature,omitempty"`

	// Extensions holds all "ext:*" fields parsed from the raw JSON.
	// Keys include the "ext:" prefix.
	Extensions map[string]any `json:"-"`
}
